# Site settings
title: Emera | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "http://mereka.github.com/maintain-a-pc/"
author:
  name: "Zabir aktar"
  email: "Zabir.aktar@gmail.com"
  url: "http://mereka.github.com/maintain-a-pc/"

# Build settings
baseurl: /maintain-a-pc/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
